# Customer Churn Prediction - Feature Engineering

## Objective

The objective of this notebook is to prepare the cleaned customer churn dataset for machine learning. This includes selecting relevant features, encoding categorical variables, handling numerical features, and creating the final dataset required for model training.

## Business Problem

Customer churn is one of the biggest challenges for telecom companies. Losing customers leads to revenue loss and increased acquisition costs. The goal of feature engineering is to transform the cleaned customer data into a machine learning-ready dataset that helps predict whether a customer is likely to churn.

## Import Required Libraries

In [33]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

## Load the Cleaned Dataset

In [34]:
df = pd.read_csv("../Dataset/processed/telco_customer_churn_cleaned.csv")

df.head()

,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,multiple_lines,internet_service,online_security,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Understand the Dataset

In [35]:
df.shape

(7043, 21)

In [36]:
df.info

<bound method DataFrame.info of      customer_id  gender  senior_citizen partner dependents  tenure  \
0     7590-VHVEG  Female               0     Yes         No       1
1     5575-GNVDE    Male               0      No         No      34
2     3668-QPYBK    Male               0      No         No       2
3     7795-CFOCW    Male               0      No         No      45
4     9237-HQITU  Female               0      No         No       2
...          ...     ...             ...     ...        ...     ...
7038  6840-RESVB    Male               0     Yes        Yes      24
7039  2234-XADUH  Female               0     Yes        Yes      72
7040  4801-JZAZL  Female               0     Yes        Yes      11
7041  8361-LTMKD    Male               1     Yes         No       4
7042  3186-AJIEK    Male               0      No         No      66

     phone_service    multiple_lines internet_service online_security  ...  \
0               No  No phone service              DSL              No  ...
1              Yes                No              DSL             Yes  ...
2              Yes                No              DSL             Yes  ...
3               No  No phone service              DSL             Yes  ...
4              Yes                No      Fiber optic              No  ...
...            ...               ...              ...             ...  ...
7038           Yes               Yes              DSL             Yes  ...
7039           Yes               Yes      Fiber optic              No  ...
7040            No  No phone service              DSL             Yes  ...
7041           Yes               Yes      Fiber optic              No  ...
7042           Yes                No      Fiber optic             Yes  ...

     device_protection tech_support streaming_tv streaming_movies  \
0                   No           No           No               No
1                  Yes           No           No               No
2                   No           No           No               No
3                  Yes          Yes           No               No
4                   No           No           No               No
...                ...          ...          ...              ...
7038               Yes          Yes          Yes              Yes
7039               Yes           No          Yes              Yes
7040                No           No           No               No
7041                No           No           No               No
7042               Yes          Yes          Yes              Yes

            contract paperless_billing             payment_method  \
0     Month-to-month               Yes           Electronic check
1           One year                No               Mailed check
2     Month-to-month               Yes               Mailed check
3           One year                No  Bank transfer (automatic)
4     Month-to-month               Yes           Electronic check
...              ...               ...                        ...
7038        One year               Yes               Mailed check
7039        One year               Yes    Credit card (automatic)
7040  Month-to-month               Yes           Electronic check
7041  Month-to-month               Yes               Mailed check
7042        Two year               Yes  Bank transfer (automatic)

     monthly_charges  total_charges  churn
0              29.85          29.85     No
1              56.95        1889.50     No
2              53.85         108.15    Yes
3              42.30        1840.75     No
4              70.70         151.65    Yes
...              ...            ...    ...
7038           84.80        1990.50     No
7039          103.20        7362.90     No
7040           29.60         346.45     No
7041           74.40         306.60    Yes
7042          105.65        6844.50     No

[7043 rows x 21 columns]>

In [37]:
df.describe()

       senior_citizen       tenure  monthly_charges  total_charges
count     7043.000000  7043.000000      7043.000000    7043.000000
mean         0.162147    32.371149        64.761692    2279.734304
std          0.368612    24.559481        30.090047    2266.794470
min          0.000000     0.000000        18.250000       0.000000
25%          0.000000     9.000000        35.500000     398.550000
50%          0.000000    29.000000        70.350000    1394.550000
75%          0.000000    55.000000        89.850000    3786.600000
max          1.000000    72.000000       118.750000    8684.800000

## Check Missing Values

In [38]:
df.isnull().sum()

customer_id          0
gender               0
senior_citizen       0
partner              0
dependents           0
tenure               0
phone_service        0
multiple_lines       0
internet_service     0
online_security      0
online_backup        0
device_protection    0
tech_support         0
streaming_tv         0
streaming_movies     0
contract             0
paperless_billing    0
payment_method       0
monthly_charges      0
total_charges        0
churn                0
dtype: int64

## Separate Features and Target Variable

In [39]:
X= df.drop("churn", axis=1)

y = df["churn"]

In [40]:
print("Features Shape :", X.shape)

print("Target Shape :", y.shape)

Features Shape : (7043, 20)
Target Shape : (7043,)

## Remove Unnecessary Features

In [41]:
X= X.drop("customer_id", axis=1)

# Conclusion

The cleaned dataset has been successfully prepared for machine learning.

The following preprocessing steps were completed:

- Loaded the cleaned customer churn dataset.
- Verified dataset quality and confirmed there are no missing values.
- Separated the feature variables (X) and target variable (y).
- Removed the customer_id column since it is a unique identifier and does not contribute to churn prediction.

Categorical encoding and numerical feature scaling will **not** be performed in this notebook. These preprocessing steps will be implemented using a **Scikit-learn Pipeline** during model training to create a reusable, production-ready machine learning workflow.